### ISSUE TITLE
CodeceptJS TestIT plugin 

### ISSUE THREAD

**Issue by alexmorez** [testit-tms/awesome-testit#1]
Привет, я сделал плагин для отправки результатов прогонов end-to-end тестов из [CodeceptJS](https://codecept.io/) в TestIT:

[codeceptjs-testit-reporter](https://github.com/alexmorez/codeceptjs-testit-reporter)

Можете посмотреть и добавить, вдруг кому еще полезно будет (:

**Comment by testit-owner** [comment]
Добрый день!
Спасибо за вашу работу. Мы добавили ссылку на ваш плагин
